//! Differential golden test for slice 2 (`context_bar_core::aggregate`):
//! `split_logical_sessions` + `bucket_aggregates` must reproduce the Python's
//! `usage_signal.py` output. The fixture was generated by driving the Python
//! functions directly with synthetic events under a FIXED `NOW` and `TZ=UTC`
//! (so local-tz bucketing is deterministic). Regenerate only with a reviewed
//! aggregation change.

use std::collections::BTreeMap;

use context_bar_core::aggregate::{bucket_aggregates, split_logical_sessions, FileEvents, TurnMetrics};
use serde_json::Value;
use time::UtcOffset;

const EPS: f64 = 1e-9;

fn u(v: &Value, k: &str) -> u64 {
    v[k].as_u64().unwrap_or_else(|| panic!("missing u64 {k} in {v}"))
}
fn f(v: &Value, k: &str) -> f64 {
    v[k].as_f64().unwrap_or_else(|| panic!("missing f64 {k} in {v}"))
}
fn s(v: &Value, k: &str) -> String {
    v[k].as_str().unwrap_or_default().to_string()
}
fn approx(a: f64, b: f64, ctx: &str) {
    assert!((a - b).abs() <= EPS + EPS * b.abs(), "{ctx}: rust={a} python={b}");
}

#[test]
fn rust_aggregate_matches_python_golden() {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/aggregate_golden.json");
    let doc: Value = serde_json::from_str(&std::fs::read_to_string(path).unwrap()).unwrap();
    let now = doc["now"].as_f64().unwrap();

    // Reconstruct the FileEvents input (sorted keys == Python insertion order).
    let mut files: BTreeMap<String, FileEvents> = BTreeMap::new();
    for (path, fv) in doc["files"].as_object().unwrap() {
        let events = fv["events"]
            .as_array()
            .unwrap()
            .iter()
            .map(|e| {
                let arr = e.as_array().unwrap();
                let ts = arr[0].as_f64().unwrap();
                let met = &arr[1];
                (
                    ts,
                    TurnMetrics {
                        total: u(met, "total"),
                        cache_read: u(met, "cache_read"),
                        input: u(met, "input"),
                        output: u(met, "output"),
                        cache_creation: u(met, "cache_creation"),
                        cost: f(met, "cost"),
                    },
                )
            })
            .collect();
        files.insert(
            path.clone(),
            FileEvents {
                model: fv["model"].as_str().map(str::to_string),
                cwd: fv["cwd"].as_str().map(str::to_string),
                events,
            },
        );
    }

    let (sessions, recent) = split_logical_sessions(&files);
    let exp = &doc["expected"];

    // --- sessions ---
    let exp_sessions = exp["sessions"].as_array().unwrap();
    assert_eq!(sessions.len(), exp_sessions.len(), "session count");
    for (i, (got, want)) in sessions.iter().zip(exp_sessions).enumerate() {
        let c = format!("session[{i}]");
        assert_eq!(got.tokens, u(want, "tokens"), "{c}.tokens");
        assert_eq!(got.cache_read, u(want, "cache_read"), "{c}.cache_read");
        assert_eq!(got.input, u(want, "input"), "{c}.input");
        assert_eq!(got.output, u(want, "output"), "{c}.output");
        assert_eq!(got.cache_creation, u(want, "cache_creation"), "{c}.cc");
        approx(got.cost, f(want, "cost"), &format!("{c}.cost"));
        approx(got.last_ts, f(want, "last_ts"), &format!("{c}.last_ts"));
        approx(got.first_ts, f(want, "first_ts"), &format!("{c}.first_ts"));
        assert_eq!(got.model.as_deref(), want["model"].as_str(), "{c}.model");
        assert_eq!(got.cwd.as_deref(), want["cwd"].as_str(), "{c}.cwd");
    }

    // --- recent (byte-exact timestamps, incl. fractional micros) ---
    let exp_recent = exp["recent"].as_array().unwrap();
    assert_eq!(recent.len(), exp_recent.len(), "recent count");
    for (i, (got, want)) in recent.iter().zip(exp_recent).enumerate() {
        let c = format!("recent[{i}]");
        assert_eq!(got.id, s(want, "id"), "{c}.id");
        assert_eq!(got.started_at, s(want, "started_at"), "{c}.started_at");
        assert_eq!(got.ended_at, s(want, "ended_at"), "{c}.ended_at");
        approx(got.duration_minutes, f(want, "duration_minutes"), &format!("{c}.dur"));
        assert_eq!(got.tokens, u(want, "tokens"), "{c}.tokens");
        approx(got.cost, f(want, "cost"), &format!("{c}.cost"));
        assert_eq!(got.model, s(want, "model"), "{c}.model");
        assert_eq!(got.project, s(want, "project"), "{c}.project");
    }

    // --- buckets ---
    let b = bucket_aggregates(&sessions, now, UtcOffset::UTC);
    let eb = &exp["buckets"];
    assert_eq!(b.total_tokens_30d, u(eb, "total_tokens_30d"), "total_tokens_30d");
    assert_eq!(b.total_sessions_30d, u(eb, "total_sessions_30d"), "total_sessions_30d");
    approx(b.total_cost_30d, f(eb, "total_cost_30d"), "total_cost_30d");
    assert_eq!(b.total_input_30d, u(eb, "total_input_30d"), "total_input_30d");
    assert_eq!(b.total_output_30d, u(eb, "total_output_30d"), "total_output_30d");
    approx(b.cost_today, f(eb, "cost_today"), "cost_today");
    approx(b.max_session_minutes, f(eb, "max_session_minutes"), "max_session_minutes");

    // by_day (365 rows, Python key "date").
    let ed = eb["by_day"].as_array().unwrap();
    assert_eq!(b.by_day.len(), ed.len(), "by_day len");
    for (i, (got, want)) in b.by_day.iter().zip(ed).enumerate() {
        let c = format!("by_day[{i}]");
        assert_eq!(got.date, s(want, "date"), "{c}.date");
        assert_eq!(got.tokens, u(want, "tokens"), "{c}.tokens");
        assert_eq!(got.sessions, u(want, "sessions"), "{c}.sessions");
        assert_eq!(got.input, u(want, "input"), "{c}.input");
        assert_eq!(got.output, u(want, "output"), "{c}.output");
        assert_eq!(got.cache_creation, u(want, "cache_creation"), "{c}.cc");
        assert_eq!(got.cache_read, u(want, "cache_read"), "{c}.cr");
        approx(got.cost, f(want, "cost"), &format!("{c}.cost"));
    }

    // by_week / by_month (Python keys "week" / "month").
    for (label, got_vec, exp_key) in [
        ("week", &b.by_week, "by_week"),
        ("month", &b.by_month, "by_month"),
    ] {
        let ev = eb[exp_key].as_array().unwrap();
        assert_eq!(got_vec.len(), ev.len(), "{exp_key} len");
        for (i, (got, want)) in got_vec.iter().zip(ev).enumerate() {
            let c = format!("{exp_key}[{i}]");
            assert_eq!(got.date, s(want, label), "{c}.label");
            assert_eq!(got.tokens, u(want, "tokens"), "{c}.tokens");
            assert_eq!(got.sessions, u(want, "sessions"), "{c}.sessions");
            assert_eq!(got.input, u(want, "input"), "{c}.input");
            assert_eq!(got.output, u(want, "output"), "{c}.output");
            assert_eq!(got.cache_creation, u(want, "cache_creation"), "{c}.cc");
            assert_eq!(got.cache_read, u(want, "cache_read"), "{c}.cr");
            approx(got.cost, f(want, "cost"), &format!("{c}.cost"));
        }
    }

    // by_model / by_project (Python keys "model" / "project").
    for (label, got_vec, exp_key) in [
        ("model", &b.by_model, "by_model"),
        ("project", &b.by_project, "by_project"),
    ] {
        let ev = eb[exp_key].as_array().unwrap();
        assert_eq!(got_vec.len(), ev.len(), "{exp_key} len");
        for (i, (got, want)) in got_vec.iter().zip(ev).enumerate() {
            let c = format!("{exp_key}[{i}]");
            assert_eq!(got.model, s(want, label), "{c}.label");
            assert_eq!(got.tokens, u(want, "tokens"), "{c}.tokens");
            assert_eq!(got.sessions, u(want, "sessions"), "{c}.sessions");
            assert_eq!(got.input, u(want, "input"), "{c}.input");
            assert_eq!(got.output, u(want, "output"), "{c}.output");
            assert_eq!(got.cache_creation, u(want, "cache_creation"), "{c}.cc");
            assert_eq!(got.cache_read, u(want, "cache_read"), "{c}.cr");
            approx(got.cost, f(want, "cost"), &format!("{c}.cost"));
        }
    }

    // by_day_project.
    let edp = eb["by_day_project"].as_array().unwrap();
    assert_eq!(b.by_day_project.len(), edp.len(), "by_day_project len");
    for (i, (got, want)) in b.by_day_project.iter().zip(edp).enumerate() {
        let c = format!("by_day_project[{i}]");
        assert_eq!(got.date, s(want, "date"), "{c}.date");
        assert_eq!(got.project, s(want, "project"), "{c}.project");
        let want_models: Vec<String> = want["models"]
            .as_array()
            .unwrap()
            .iter()
            .map(|m| m.as_str().unwrap().to_string())
            .collect();
        assert_eq!(got.models, want_models, "{c}.models");
        assert_eq!(got.tokens, u(want, "tokens"), "{c}.tokens");
        assert_eq!(got.sessions, u(want, "sessions"), "{c}.sessions");
        assert_eq!(got.input, u(want, "input"), "{c}.input");
        assert_eq!(got.output, u(want, "output"), "{c}.output");
        assert_eq!(got.cache_creation, u(want, "cache_creation"), "{c}.cc");
        assert_eq!(got.cache_read, u(want, "cache_read"), "{c}.cr");
        approx(got.cost, f(want, "cost"), &format!("{c}.cost"));
    }

    eprintln!(
        "aggregate golden: {} sessions, {} recent, by_day {}, weeks {}, months {}, models {}, projects {}, instances {} — all match",
        sessions.len(), recent.len(), b.by_day.len(), b.by_week.len(), b.by_month.len(),
        b.by_model.len(), b.by_project.len(), b.by_day_project.len(),
    );
}
