//! Differential golden test: the Rust cost kernel (`context_bar_core::pricing`)
//! must reproduce `usage_signal.py`'s pricing byte-for-byte. The fixture in
//! `tests/fixtures/pricing_golden.json` was generated by driving the Python's
//! `match_pricing` / `turn_cost` / `turn_cache_savings` against the bundled
//! `FALLBACK_PRICING` table over a model × token grid. Regenerate it (see the
//! generator in the repo history) only with a deliberate, reviewed cost change.

use context_bar_core::pricing::{fallback_table, match_pricing, turn_cache_savings, turn_cost};
use serde_json::Value;

#[test]
fn rust_kernel_matches_python_golden() {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/pricing_golden.json");
    let raw = std::fs::read_to_string(path).expect("read golden fixture");
    let doc: Value = serde_json::from_str(&raw).expect("parse golden fixture");
    let rows = doc["rows"].as_array().expect("rows array");
    assert!(!rows.is_empty(), "fixture has no rows");

    // Both sides are f64 with identical operation order, so results should be
    // bit-identical; allow a hair of slack for any formatting round-trip.
    const EPS: f64 = 1e-9;

    let table = fallback_table();
    let mut checked = 0usize;
    for row in rows {
        let model = row["model"].as_str().unwrap();
        let inp = row["inp"].as_u64().unwrap();
        let cc = row["cache_create"].as_u64().unwrap();
        let cr = row["cache_read"].as_u64().unwrap();
        let outp = row["outp"].as_u64().unwrap();
        let want_matched = row["matched"].as_bool().unwrap();
        let want_cost = row["cost"].as_f64().unwrap();
        let want_savings = row["savings"].as_f64().unwrap();

        let rate = match_pricing(model, &table);
        assert_eq!(
            rate.is_some(),
            want_matched,
            "match mismatch for {model:?}: rust={:?} python={want_matched}",
            rate.is_some()
        );

        let cost = turn_cost(rate.as_ref(), inp, cc, cr, outp);
        assert!(
            (cost - want_cost).abs() <= EPS + EPS * want_cost.abs(),
            "cost mismatch for {model:?} ({inp},{cc},{cr},{outp}): rust={cost} python={want_cost}"
        );

        let savings = turn_cache_savings(rate.as_ref(), cc, cr);
        assert!(
            (savings - want_savings).abs() <= EPS + EPS * want_savings.abs(),
            "savings mismatch for {model:?} ({cc},{cr}): rust={savings} python={want_savings}"
        );
        checked += 1;
    }
    assert_eq!(checked, rows.len());
    eprintln!("pricing golden: {checked} rows matched Python byte-for-byte");
}
